server:
  port: 9090

api:
  receitaws:
    url: https://receitaws.com.br/v1/cnpj
  brasilapi:
    url: https://brasilapi.com.br/api/cnpj/v1
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev

  application:
    name: processador-cnpj

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://nexdb.cgrfqoqnbezc.sa-east-1.rds.amazonaws.com:13813/nexdb_production
    username: root
    password: 3TN2bvZrYT6J474We8Kd
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
